"""Add HistoryTick schema

Revision ID: 8e072f44539b
Revises: 
Create Date: 2024-11-18 18:01:59.794913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e072f44539b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_tick',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('bid_price', sa.Float(), nullable=True),
    sa.Column('bid_volume', sa.Integer(), nullable=True),
    sa.Column('ask_price', sa.Float(), nullable=True),
    sa.Column('ask_volume', sa.Integer(), nullable=True),
    sa.Column('tick_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'ts'),
    postgresql_partition_by='RANGE(ts)'
    )
    op.create_index(op.f('ix_history_tick_symbol'), 'history_tick', ['symbol'], unique=False)
    op.create_index(op.f('ix_history_tick_ts'), 'history_tick', ['ts'], unique=False)
    op.create_table('history_tick_memo',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_tick_memo')
    op.drop_index(op.f('ix_history_tick_ts'), table_name='history_tick')
    op.drop_index(op.f('ix_history_tick_symbol'), table_name='history_tick')
    op.drop_table('history_tick')
    # ### end Alembic commands ###
