"""add kbar related schemas

Revision ID: ae42efa18be5
Revises: 8e072f44539b
Create Date: 2025-08-13 16:34:19.656119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae42efa18be5'
down_revision: Union[str, None] = '8e072f44539b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k_bar',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'ts'),
    postgresql_partition_by='RANGE(ts)'
    )
    op.create_index(op.f('ix_k_bar_symbol'), 'k_bar', ['symbol'], unique=False)
    op.create_index(op.f('ix_k_bar_ts'), 'k_bar', ['ts'], unique=False)
    op.create_table('k_bar_memo',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'symbol')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('k_bar_memo')
    op.drop_index(op.f('ix_k_bar_ts'), table_name='k_bar')
    op.drop_index(op.f('ix_k_bar_symbol'), table_name='k_bar')
    op.drop_table('k_bar')
    # ### end Alembic commands ###
