# Form implementation generated from reading ui file 'shio_trade_monitor.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(835, 731)
        Dialog.setStyleSheet("QWidget {\n"
"    background-color: #2f2f2f; /* 非常深的灰色背景 */\n"
"    color: #00ff00; /* 亮綠色字體 */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #1f1f1f; /* 更深灰色按鈕背景 */\n"
"    color: #00ff00; /* 亮綠色字體 */\n"
"    border: 1px solid #00ff00; /* 亮綠色邊框 */\n"
"    border-radius: 4px; /* 圓角按鈕 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #141414; /* 滑鼠懸停時按鈕背景 */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #3f3f3f; /* 輸入框背景 */\n"
"    color: #00ff00; /* 輸入框文字顏色 */\n"
"    border: 1px solid #00ff00; /* 輸入框邊框 */\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #00ff00; /* 標籤文字顏色 */\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    background-color: #3f3f3f; /* 文本框背景 */\n"
"    color: #00ff00; /* 文本框字體顏色 */\n"
"    border: 1px solid #00ff00; /* 文本框邊框 */\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.textBrowserIndicaor = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowserIndicaor.setGeometry(QtCore.QRect(10, 37, 601, 241))
        self.textBrowserIndicaor.setObjectName("textBrowserIndicaor")
        self.textBrowserDeals = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowserDeals.setGeometry(QtCore.QRect(10, 316, 601, 171))
        self.textBrowserDeals.setObjectName("textBrowserDeals")
        self.labelIndicaor = QtWidgets.QLabel(parent=Dialog)
        self.labelIndicaor.setGeometry(QtCore.QRect(10, 6, 61, 31))
        self.labelIndicaor.setObjectName("labelIndicaor")
        self.labelDeals = QtWidgets.QLabel(parent=Dialog)
        self.labelDeals.setGeometry(QtCore.QRect(10, 290, 58, 21))
        self.labelDeals.setObjectName("labelDeals")
        self.textBrowserSignals = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowserSignals.setGeometry(QtCore.QRect(10, 526, 601, 171))
        self.textBrowserSignals.setObjectName("textBrowserSignals")
        self.labelSignals = QtWidgets.QLabel(parent=Dialog)
        self.labelSignals.setGeometry(QtCore.QRect(10, 500, 58, 21))
        self.labelSignals.setObjectName("labelSignals")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowserIndicaor.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[Indicators]</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">| newest price: 23359.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">| 3600.0_s_ma: 23361.877800407332 | short_ma: 23355.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">| atr: 2.7560975609756095</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[Vol avg info (l=3600.0 s)]</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">start: 03:25:05 | end: 04:24:26</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">| avg: 0.6819444444444445 | per: 0:00:05 | delta:0:59:20.565000</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">| 381 ticks</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[Vol avg info (l=30.0 s)]</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">start: 04:23:56 | end: 04:24:26</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">| avg: 0.8333333333333334 | per: 0:00:05 | delta:0:00:29.881000</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">| 5 ticks</p></body></html>"))
        self.labelIndicaor.setText(_translate("Dialog", "Indicator"))
        self.labelDeals.setText(_translate("Dialog", "Deals"))
        self.labelSignals.setText(_translate("Dialog", "Signals"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
